import { action, query, mutation, internalQuery, internalMutation } from './_generated/server';
import { v, ConvexError } from 'convex/values';
import { paginationOptsValidator } from 'convex/server';
import { internal } from './_generated/api';
import { requireBusinessAccess, getActor, getAccessibleBusinesses } from './lib/accountantAccess';
import { aggregate } from '../shared/compliance/aggregate';
import { configuration, TT_FIELDS, BB_FIELDS, IT76_FIELDS } from '../shared/compliance/registry';
const yearArgs={businessId:v.id('businesses'),taxYear:v.number(),month:v.optional(v.string())};
export const clients = query({args:{},handler:async ctx=>{const {actor}=await getActor(ctx);return (await getAccessibleBusinesses(ctx,actor._id)).map((b:any)=>({id:b._id,name:b.name,country:b.countryCode}));}});
export const context = internalQuery({args:yearArgs,handler:async(ctx,args)=>{
 const business=await ctx.db.get(args.businessId);const access=await requireBusinessAccess(ctx,business,'read');configuration(business!.countryCode||'',args.taxYear);
 const reviews=await ctx.db.query('complianceReviews').withIndex('by_business_year',q=>q.eq('businessId',args.businessId).eq('taxYear',args.taxYear)).collect();
 const generations=await ctx.db.query('complianceGenerations').withIndex('by_business_year',q=>q.eq('businessId',args.businessId).eq('taxYear',args.taxYear)).order('desc').take(20);
 return {business,reviews,generations:generations.filter(g=>g.status!=='building').map(g=>({formId:g.formId,status:g.status,month:g.month,createdAt:g.createdAt,fingerprint:JSON.stringify(g.sourceRuns.map((r:any)=>[r.id,r.updatedAt]).sort((a:any,b:any)=>String(a[0]).localeCompare(String(b[0]))))})),actor:access.actor._id,owner:access.owner._id,canGenerate:['Owner','Admin','Payroll Manager','Payroll Assistant'].includes(access.role)};
}});
export const payrollPage = internalQuery({args:{...yearArgs,paginationOpts:paginationOptsValidator},handler:async(ctx,args)=>{await requireBusinessAccess(ctx,await ctx.db.get(args.businessId),'read');return ctx.db.query('payrollRuns').withIndex('by_business_year',q=>q.eq('businessId',args.businessId).eq('year',args.taxYear)).paginate(args.paginationOpts);}});
export const employeePage = internalQuery({args:{businessId:v.id('businesses'),paginationOpts:paginationOptsValidator},handler:async(ctx,args)=>{await requireBusinessAccess(ctx,await ctx.db.get(args.businessId),'read');return ctx.db.query('employees').withIndex('by_business',q=>q.eq('businessId',args.businessId)).paginate(args.paginationOpts);}});
async function build(ctx:any,args:any):Promise<any>{
 if(args.month && !['January','February','March','April','May','June','July','August','September','October','November','December'].includes(args.month))throw new ConvexError('Select a valid month.');
 const data=await ctx.runQuery((internal as any).compliance.context,args);const runs:any[]=[],employees:any[]=[];
 for(const kind of ['payroll','employee']){let cursor=null;do{const page:any=await ctx.runQuery((internal as any).compliance[kind+'Page'],{...(kind==='payroll'?args:{businessId:args.businessId}),paginationOpts:{cursor,numItems:kind==='payroll'?10:100}});(kind==='payroll'?runs:employees).push(...page.page);cursor=page.isDone?null:page.continueCursor;}while(cursor);}
 const report=aggregate(data.business,args.taxYear,runs,employees,data.reviews,args.month);const current=data.generations.filter((g:any)=>g.fingerprint===report.fingerprint&&g.month===report.month);return {...report,ready:report.status==='Ready',status:report.status==='Ready'&&current.length?current[0].status:report.status,lastGeneratedAt:data.generations[0]?.createdAt||null,canGenerate:data.canGenerate,forms:report.forms.map((f:any)=>({...f,status:!f.issues.length&&current.find((g:any)=>g.formId===f.id)?current.find((g:any)=>g.formId===f.id).status:f.status}))};
}
export const overview = action({args:yearArgs,handler:(ctx,args)=>build(ctx,args)});
export const saveEmployer = mutation({args:{businessId:v.id('businesses'),address:v.string(),taxRegistrationId:v.string(),nisNumber:v.string(),payeNumber:v.string()},handler:async(ctx,args)=>{await requireBusinessAccess(ctx,await ctx.db.get(args.businessId),'manageClients');for(const x of Object.values(args))if(typeof x==='string' && x.length>1000)throw new ConvexError('Field too long.');await ctx.db.patch(args.businessId,{address:args.address.trim(),taxRegistrationId:args.taxRegistrationId.trim(),nisNumber:args.nisNumber.trim(),compliancePayeNumber:args.payeNumber.trim(),updatedAt:Date.now()});}});
export const saveEmployee = mutation({args:{businessId:v.id('businesses'),employeeId:v.id('employees'),address:v.string(),taxId:v.string(),contributionId:v.string()},handler:async(ctx,args)=>{
 await requireBusinessAccess(ctx,await ctx.db.get(args.businessId),'manageEmployees');const employee=await ctx.db.get(args.employeeId);if(!employee || employee.businessId!==args.businessId)throw new ConvexError('Employee not found.');if([args.address,args.taxId,args.contributionId].some(x=>x.length>1000))throw new ConvexError('Field too long.');await ctx.db.patch(args.employeeId,{address:args.address.trim(),payrollIdentifiers:{...(employee.payrollIdentifiers||{}),primaryId:args.taxId.trim(),taxId:args.taxId.trim(),secondaryId:args.contributionId.trim()}});
}});
export const saveReview = mutation({args:{...yearArgs,employeeId:v.id('employees'),values:v.any(),fingerprint:v.string(),confirmed:v.boolean()},handler:async(ctx,args)=>{
 const business=await ctx.db.get(args.businessId);const {actor}=await requireBusinessAccess(ctx,business,'editPayroll');configuration(business!.countryCode||'',args.taxYear);
 const employee=await ctx.db.get(args.employeeId);if(!employee||employee.businessId!==args.businessId)throw new ConvexError('Employee not found.');if(JSON.stringify(args.values).length>20000||args.fingerprint.length>200000)throw new ConvexError('Review too large.');
 const allowed=new Set([...TT_FIELDS.map(x=>x[0]),...BB_FIELDS.map(x=>x[0]),'benefits']);for(const[k,value]of Object.entries(args.values)){if(!allowed.has(k))throw new ConvexError('Unknown review field.');if(k!=='benefits'&&typeof value!=='number'&&typeof value!=='string')throw new ConvexError('Invalid review value.');}if(args.values.benefits){const fields=new Set([...IT76_FIELDS.map(x=>x[0]),'personType','owned']);for(const k of Object.keys(args.values.benefits))if(!fields.has(k))throw new ConvexError('Unknown benefit field.');}
 const rows=await ctx.db.query('complianceReviews').withIndex('by_business_year',q=>q.eq('businessId',args.businessId).eq('taxYear',args.taxYear)).collect();const before=rows.find(r=>r.employeeId===String(args.employeeId)&&r.month===(args.month||''));const value={businessId:args.businessId,employeeId:String(args.employeeId),taxYear:args.taxYear,month:args.month||'',values:args.values,fingerprint:args.fingerprint,confirmed:args.confirmed,reviewedBy:actor._id,updatedAt:Date.now()};if(before)await ctx.db.patch(before._id,value);else await ctx.db.insert('complianceReviews',value);
}});
export const begin = internalMutation({args:{...yearArgs,formId:v.string(),data:v.any(),employeeIds:v.array(v.string())},handler:async(ctx,args)=>{
 const {actor,owner}=await requireBusinessAccess(ctx,await ctx.db.get(args.businessId),'editPayroll');
 for(const ref of args.data.trace){const run:any=await ctx.db.get(ref.id);if(!run||run.updatedAt!==ref.updatedAt||run.businessId!==args.businessId)throw new ConvexError('Payroll changed. Refresh validation before generating.');}
 return ctx.db.insert('complianceGenerations',{businessId:args.businessId,workspaceOwnerId:owner._id,actorId:actor._id,taxYear:args.taxYear,month:args.month||'',formId:args.formId,version:args.data.config.version,config:args.data.config,summary:{business:args.data.business,totals:args.data.totals,history:args.data.history,reconciliation:args.data.reconciliation,monthly:args.data.monthly,periodCount:args.data.periodCount},sourceRuns:args.data.trace,employeeIds:args.employeeIds,status:'building',createdAt:Date.now()});
}});
export const append = internalMutation({args:{generationId:v.id('complianceGenerations'),records:v.array(v.any()),offset:v.number(),complete:v.boolean()},handler:async(ctx,args)=>{
 const g=await ctx.db.get(args.generationId);if(!g||g.status!=='building')throw new ConvexError('Generation unavailable.');await requireBusinessAccess(ctx,await ctx.db.get(g.businessId),'editPayroll');
 for(let i=0;i<args.records.length;i++)await ctx.db.insert('complianceGeneratedRows',{generationId:g._id,ordinal:args.offset+i,record:args.records[i]});
 if(args.complete){for(const ref of g.sourceRuns){const run:any=await ctx.db.get(ref.id);if(!run||run.updatedAt!==ref.updatedAt)throw new ConvexError('Payroll changed during generation. Refresh and retry.');}await ctx.db.patch(g._id,{status:'Generated',completedAt:Date.now()});await ctx.db.insert('complianceAudit',{generationId:g._id,businessId:g.businessId,actorId:g.actorId,event:'Generated',createdAt:Date.now()});}
}});
export const generate = action({args:{...yearArgs,formId:v.string(),employeeIds:v.optional(v.array(v.string()))},handler:async(ctx,args):Promise<any>=>{
 const data=await build(ctx,{businessId:args.businessId,taxYear:args.taxYear,...(args.month?{month:args.month}:{})});const form=data.forms.find((f:any)=>f.id===args.formId);if(!form)throw new ConvexError('Unknown compliance report.');
 const ids=args.employeeIds;const selected=ids?.length?data.employees.filter((e:any)=>ids.includes(e.id)):data.employees;if(ids && (new Set(ids).size!==ids.length||selected.length!==ids.length))throw new ConvexError('Select valid client employees.');
 const relevant=form.issues.filter((i:any)=>!ids?.length||!['employee','review'].includes(i.entity)||ids.includes(i.id));if(relevant.length||!data.reconciled)throw new ConvexError({code:'COMPLIANCE_NOT_READY',message:'Resolve missing data, payroll review and reconciliation issues before generation.',issues:relevant});
 if(args.formId==='annual_pack'){const failed=data.forms.filter((f:any)=>['td4','it76','tamis_paye'].includes(f.id)&&f.issues.length); // Packs remain preparation reports if official forms are not ready.
 data.config={...data.config,packOfficialForms:data.forms.filter((f:any)=>!f.issues.length&&['td4','it76'].includes(f.id)).map((f:any)=>f.id),packExcludedForms:failed.map((f:any)=>f.name)};}
 const generationId=await ctx.runMutation((internal as any).compliance.begin,{businessId:args.businessId,taxYear:args.taxYear,...(args.month?{month:args.month}:{}),formId:args.formId,data:{...data,employees:[],forms:[],issues:[]},employeeIds:selected.map((e:any)=>e.id)});
 for(let offset=0;offset<selected.length;offset+=50)await ctx.runMutation((internal as any).compliance.append,{generationId,records:selected.slice(offset,offset+50),offset,complete:offset+50>=selected.length});
 return {generationId,employeeCount:selected.length};
}});
export const history = query({args:{businessId:v.id('businesses'),taxYear:v.number(),employeeId:v.optional(v.string())},handler:async(ctx,args)=>{await requireBusinessAccess(ctx,await ctx.db.get(args.businessId),'read');return (await ctx.db.query('complianceGenerations').withIndex('by_business_year',q=>q.eq('businessId',args.businessId).eq('taxYear',args.taxYear)).order('desc').take(100)).filter(g=>g.status!=='building'&&(!args.employeeId||g.employeeIds.includes(args.employeeId))).map(g=>({id:g._id,formId:g.formId,status:g.status,createdAt:g.createdAt,version:g.version,employeeCount:g.employeeIds.length,month:g.month}));}});
export const generatedPage = query({args:{generationId:v.id('complianceGenerations'),paginationOpts:paginationOptsValidator},handler:async(ctx,args)=>{const g=await ctx.db.get(args.generationId);if(!g||g.status==='building')throw new ConvexError('Generated report unavailable.');await requireBusinessAccess(ctx,await ctx.db.get(g.businessId),'read');const rows=await ctx.db.query('complianceGeneratedRows').withIndex('by_generation',q=>q.eq('generationId',g._id)).paginate(args.paginationOpts);return {generation:g,rows};}});
export const recordExport = mutation({args:{generationId:v.id('complianceGenerations'),format:v.union(v.literal('PDF'),v.literal('ZIP'),v.literal('CSV'),v.literal('XLSX'),v.literal('Print'))},handler:async(ctx,args)=>{const g=await ctx.db.get(args.generationId);if(!g||g.status==='building')throw new ConvexError('Generated report unavailable.');const {actor}=await requireBusinessAccess(ctx,await ctx.db.get(g.businessId),'read');await ctx.db.insert('complianceAudit',{generationId:g._id,businessId:g.businessId,actorId:actor._id,event:'Exported',format:args.format,createdAt:Date.now()});await ctx.db.patch(g._id,{status:'Exported'});}});
