// Deployment-only fixtures. Internal functions are inaccessible to browser clients.
import { internalMutation } from './_generated/server';
import { v } from 'convex/values';
import { TT_FIELDS, BB_FIELDS } from '../shared/compliance/registry';
import { aggregate } from '../shared/compliance/aggregate';
const args={firebaseUid:v.string(),email:v.string()};
function check(email:string){if(!/^sheetpay-compliance-[a-f0-9-]{36}@example\.invalid$/.test(email))throw Error('Synthetic verification identity required.');}
export const seed=internalMutation({args,handler:async(ctx,a)=>{check(a.email);if(await ctx.db.query('users').withIndex('by_firebase_uid',q=>q.eq('firebaseUid',a.firebaseUid)).first())throw Error('Identity already exists.');const now=Date.now(),year=new Date().getUTCFullYear();const user=await ctx.db.insert('users',{firebaseUid:a.firebaseUid,email:a.email,accountType:'accountant',plan:'free',planStatus:'none',onboardingCompleted:true,createdAt:now,marketingUnsubscribedAt:now});const clients:any[]=[];
for(const country of ['TT','LC','BB','BZ']){const b=await ctx.db.insert('businesses',{userId:user,name:'Compliance Verification '+country,countryCode:country,currency:country==='TT'?'TTD':country==='BB'?'BBD':country==='BZ'?'BZD':'XCD',currencySymbol:'$',address:'Synthetic verification address',taxRegistrationId:country==='BB'?'1000012345678':'1234567890',nisNumber:'12345',compliancePayeNumber:'PYE-12345678',updatedAt:now});const employee={businessId:b,userId:user,name:'Synthetic Verification Employee',employeeId:'VERIFY-1',position:'Verification',department:'Verification',address:'Synthetic employee address',payFrequency:'Monthly',basicPay:900,frequencySalary:900,overtimeHours:2,overtimeRate:25,bonus:20,commission:10,allowances:20,paye:100,nis:50,healthSurcharge:0,otherDeductions:10,grossPay:1000,netPay:840,status:'active',localId:'verify-1',createdAt:now,payrollIdentifiers:{primaryId:country==='BB'?'1000012345678':'1234567890',secondaryId:'123456789'},statutoryData:{pension:10,employerContribution:50,taxableEarnings:1000}};const id=await ctx.db.insert('employees',employee);const snapshot={...employee,_id:id};const rid=await ctx.db.insert('payrollRuns',{businessId:b,userId:user,month:'January',year,periodLabel:'January synthetic verification',status:'finalized',employeesSnapshot:[snapshot],totalGross:1000,totalPaye:100,totalNis:50,totalHealthSurcharge:0,totalDeductions:160,totalNet:840,createdAt:now,updatedAt:now});const run=await ctx.db.get(rid),business=await ctx.db.get(b);const d=aggregate(business,year,[run],[snapshot]);if(country==='TT'||country==='BB'){const values:any=Object.fromEntries((country==='TT'?[...TT_FIELDS]:[...BB_FIELDS]).map(x=>[x[0],0]));if(country==='TT')Object.assign(values,{weeksEmployed:1,remuneration:970,commissions:10,otherAllowance:20,employeePension:10});else Object.assign(values,{taxCode:'1000',employmentStart:`${year}-01-01`,employmentEnd:'',pension:10,travel:20,basicMonthlySalary:900});await ctx.db.insert('complianceReviews',{businessId:b,employeeId:String(id),taxYear:year,month:country==='BB'?'January':'',values,confirmed:true,fingerprint:d.fingerprint,reviewedBy:user,updatedAt:now});}clients.push({id:b,country,employeeId:id});}
return {clients,taxYear:year};}});
export const cleanup=internalMutation({args,handler:async(ctx,a)=>{check(a.email);const user=await ctx.db.query('users').withIndex('by_firebase_uid',q=>q.eq('firebaseUid',a.firebaseUid)).first();if(!user)return;if(user.email!==a.email||!user.marketingUnsubscribedAt)throw Error('Fixture identity mismatch.');const businesses=await ctx.db.query('businesses').withIndex('by_user',q=>q.eq('userId',user._id)).collect();for(const b of businesses){if(!/^Compliance Verification (TT|LC|BB|BZ)$/.test(b.name))throw Error('Unexpected verification client.');const gens=await ctx.db.query('complianceGenerations').withIndex('by_business_year',q=>q.eq('businessId',b._id)).collect();for(const g of gens){for(const row of await ctx.db.query('complianceGeneratedRows').withIndex('by_generation',q=>q.eq('generationId',g._id)).collect())await ctx.db.delete(row._id);for(const row of await ctx.db.query('complianceAudit').withIndex('by_generation',q=>q.eq('generationId',g._id)).collect())await ctx.db.delete(row._id);await ctx.db.delete(g._id);}for(const row of await ctx.db.query('complianceReviews').withIndex('by_business_year',q=>q.eq('businessId',b._id)).collect())await ctx.db.delete(row._id);for(const row of await ctx.db.query('payrollRuns').withIndex('by_business_year',q=>q.eq('businessId',b._id)).collect())await ctx.db.delete(row._id);for(const row of await ctx.db.query('employees').withIndex('by_business',q=>q.eq('businessId',b._id)).collect())await ctx.db.delete(row._id);await ctx.db.delete(b._id);}await ctx.db.delete(user._id);return {removed:true};}});
