/// <reference types="vite/client" />
import { describe, it, expect } from 'vitest';
import { convexTest } from 'convex-test';
import { anyApi } from 'convex/server';
import schema from '../convex/schema';
import { aggregate } from '../shared/compliance/aggregate';
import { TT_FIELDS, BB_FIELDS, configuration } from '../shared/compliance/registry';
const modules=import.meta.glob('../convex/**/*.{ts,js}');
async function fixture(country='TT',count=1,periods=1){const t=convexTest(schema,modules);const ids=await t.run(async ctx=>{const owner=await ctx.db.insert('users',{firebaseUid:'compliance-owner',email:'owner@example.com',accountType:'accountant',plan:'free'});const other=await ctx.db.insert('users',{firebaseUid:'compliance-other',email:'other@example.com'});const b=await ctx.db.insert('businesses',{userId:owner,name:'Trini Builders',countryCode:country,currency:country==='TT'?'TTD':country==='BB'?'BBD':country==='BZ'?'BZD':'XCD',currencySymbol:'$',address:'123 Long Street',taxRegistrationId:country==='BB'?'1000012345678':'1234567890',nisNumber:'12345',compliancePayeNumber:'PYE-12345678',updatedAt:1});const rows:any[]=[];for(let i=0;i<count;i++){const row={businessId:b,userId:owner,name:'Employee '+i,employeeId:'EMP'+i,position:'Builder',department:'Site',address:'Employee address',payFrequency:i%3===0?'Weekly':i%3===1?'Fortnightly':'Monthly',basicPay:900,frequencySalary:900,overtimeHours:2,overtimeRate:25,bonus:20,commission:10,allowances:20,paye:100,nis:50,healthSurcharge:0,otherDeductions:10,grossPay:1000,netPay:840,status:'active',localId:String(i),createdAt:1,payrollIdentifiers:{primaryId:country==='BB'?'1000012345678':'1234567890',secondaryId:'123456789'},statutoryData:{pension:10,employerContribution:50,taxableEarnings:1000}};const _id=await ctx.db.insert('employees',row);rows.push({...row,_id});}const runs=[];for(let i=0;i<periods;i++)runs.push(await ctx.db.insert('payrollRuns',{businessId:b,userId:owner,month:i%2?'February':'January',year:2026,periodLabel:'Period '+i,status:'finalized',employeesSnapshot:rows,totalGross:count*1000,totalPaye:count*100,totalNis:count*50,totalHealthSurcharge:0,totalDeductions:count*160,totalNet:count*840,createdAt:1,updatedAt:i+1}));return {owner,other,b,rows,runs};});return {t,ids,owner:t.withIdentity({subject:'compliance-owner',email:'owner@example.com'}),other:t.withIdentity({subject:'compliance-other',email:'other@example.com'})};}
describe('Tax & Compliance aggregation, authorization and snapshots',()=>{
 for(const country of ['TT','LC','BB','BZ'])it(`${country} aggregates 50 employees, frequencies, bonuses, overtime, allowances and pension from 52 payroll periods`,async()=>{const {owner,ids}=await fixture(country,50,52);const d=await owner.action(anyApi.compliance.overview,{businessId:ids.b,taxYear:2026});expect(d.employeeCount).toBe(50);expect(d.periodCount).toBe(52);expect(d.totals).toMatchObject({gross:260000000,paye:26000000,contribution:13000000,bonus:5200000,overtime:13000000,allowances:5200000,pension:2600000});expect(d.reconciled).toBe(true);expect(d.issues).toEqual([]);expect(d.trace).toHaveLength(52);});
 it('blocks generation when payroll totals disagree, statutory amounts missing or payroll is draft',async()=>{const {t,owner,ids}=await fixture();await t.run(ctx=>ctx.db.patch(ids.runs[0],{totalGross:1001}));let d=await owner.action(anyApi.compliance.overview,{businessId:ids.b,taxYear:2026});expect(d.reconciled).toBe(false);await expect(owner.action(anyApi.compliance.generate,{businessId:ids.b,taxYear:2026,formId:'annual_pack'})).rejects.toThrow('COMPLIANCE_NOT_READY');await t.run(ctx=>ctx.db.patch(ids.runs[0],{status:'Draft',totalGross:1000}));d=await owner.action(anyApi.compliance.overview,{businessId:ids.b,taxYear:2026});expect(d.issues.some((i:any)=>i.code==='DRAFT_PAYROLL')).toBe(true);expect(d.employeeCount).toBe(0);});
 it('flags missing employee IDs, tax IDs and contribution numbers',async()=>{const {t,owner,ids}=await fixture();await t.run(ctx=>ctx.db.patch(ids.rows[0]._id,{employeeId:'',payrollIdentifiers:{}}));const d=await owner.action(anyApi.compliance.overview,{businessId:ids.b,taxYear:2026});expect(d.issues[0].message).toContain('employee ID, tax ID, contribution number');expect(d.status).toBe('Missing Data');});
 it('persists reproducible snapshots, checks source edits and records exports under existing authorization',async()=>{const {t,owner,other,ids}=await fixture();const g=await owner.action(anyApi.compliance.generate,{businessId:ids.b,taxYear:2026,formId:'annual_pack'});let saved=await owner.query(anyApi.compliance.generatedPage,{generationId:g.generationId,paginationOpts:{cursor:null,numItems:50}});expect(saved.rows.page[0].record.totals.gross).toBe(100000);expect(saved.generation.config.packExcludedForms).toContain('TD4 Certificates');await t.run(ctx=>ctx.db.patch(ids.runs[0],{updatedAt:9,totalGross:1001}));saved=await owner.query(anyApi.compliance.generatedPage,{generationId:g.generationId,paginationOpts:{cursor:null,numItems:50}});expect(saved.generation.summary.totals.gross).toBe(100000);await owner.mutation(anyApi.compliance.recordExport,{generationId:g.generationId,format:'PDF'});expect((await owner.query(anyApi.compliance.history,{businessId:ids.b,taxYear:2026}))[0].status).toBe('Exported');await expect(other.action(anyApi.compliance.overview,{businessId:ids.b,taxYear:2026})).rejects.toThrow();await expect(other.query(anyApi.compliance.generatedPage,{generationId:g.generationId,paginationOpts:{cursor:null,numItems:50}})).rejects.toThrow();await expect(other.mutation(anyApi.compliance.recordExport,{generationId:g.generationId,format:'CSV'})).rejects.toThrow();await expect(t.action(anyApi.compliance.overview,{businessId:ids.b,taxYear:2026})).rejects.toThrow();});
 it('TD4 requires explicit reviewed mappings, then invalidates review after payroll edits',async()=>{const {t,owner,ids}=await fixture();const d=await owner.action(anyApi.compliance.overview,{businessId:ids.b,taxYear:2026});await expect(owner.action(anyApi.compliance.generate,{businessId:ids.b,taxYear:2026,formId:'td4'})).rejects.toThrow();const values:any=Object.fromEntries(TT_FIELDS.map(([k])=>[k,0]));Object.assign(values,{weeksEmployed:1,remuneration:970,commissions:10,otherAllowance:20,employeePension:10});await owner.mutation(anyApi.compliance.saveReview,{businessId:ids.b,taxYear:2026,employeeId:ids.rows[0]._id,values,fingerprint:d.fingerprint,confirmed:true});const g=await owner.action(anyApi.compliance.generate,{businessId:ids.b,taxYear:2026,formId:'td4'});expect(g.employeeCount).toBe(1);await t.run(ctx=>ctx.db.patch(ids.runs[0],{updatedAt:99}));await expect(owner.action(anyApi.compliance.generate,{businessId:ids.b,taxYear:2026,formId:'td4'})).rejects.toThrow();});
 it('TAMIS requires a monthly review and preserves the actual template mapping data',async()=>{const {owner,ids}=await fixture('BB');const d=await owner.action(anyApi.compliance.overview,{businessId:ids.b,taxYear:2026,month:'January'});const values:any=Object.fromEntries(BB_FIELDS.map(([k])=>[k,0]));Object.assign(values,{taxCode:'1000',employmentStart:'2025-06-01',employmentEnd:'',pension:10,travel:20,basicMonthlySalary:900});await owner.mutation(anyApi.compliance.saveReview,{businessId:ids.b,taxYear:2026,month:'January',employeeId:ids.rows[0]._id,values,fingerprint:d.fingerprint,confirmed:true});expect((await owner.action(anyApi.compliance.generate,{businessId:ids.b,taxYear:2026,month:'January',formId:'tamis_paye'})).employeeCount).toBe(1);await expect(owner.action(anyApi.compliance.generate,{businessId:ids.b,taxYear:2026,formId:'tamis_paye'})).rejects.toThrow();});
 it('handles joiners, leavers, historical years and unknown pension without extrapolating earnings',()=>{const business={_id:'b',name:'Company',countryCode:'LC',currency:'XCD',address:'a',taxRegistrationId:'123',nisNumber:'321'};const a={_id:'a',name:'Joined June',employeeId:'A',address:'a',payrollIdentifiers:{primaryId:'123',secondaryId:'321'},grossPay:100,netPay:80,paye:10,nis:10,healthSurcharge:0,otherDeductions:0,basicPay:100,bonus:0,commission:0,allowances:0};const b={...a,_id:'b',name:'Left July',employeeId:'B'};const runs=[{_id:'r1',year:2025,month:'June',status:'paid',employeesSnapshot:[a,b],totalGross:200,totalNet:160,totalPaye:20,totalNis:20,totalHealthSurcharge:0,totalDeductions:40,updatedAt:1},{_id:'r2',year:2025,month:'July',status:'paid',employeesSnapshot:[a],totalGross:100,totalNet:80,totalPaye:10,totalNis:10,totalHealthSurcharge:0,totalDeductions:20,updatedAt:2}];const d=aggregate(business,2025,runs,[a,b]);expect(d.totals.gross).toBe(30000);expect(d.totals.pension).toBe(null);expect(d.employees.map(e=>e.periods)).toEqual([2,1]);expect(configuration('LC',2025).version).not.toBe(configuration('LC',2026).version);expect(d.forms.find(f=>f.id==='td5').issues.some((i:any)=>i.code==='SPECIFICATION')).toBe(true);expect(()=>configuration('TT',2027)).toThrow();});
 it('Viewer cannot generate or alter tax data',async()=>{const {t,other,ids}=await fixture();await t.run(ctx=>ctx.db.insert('accountantMemberships',{workspaceOwnerId:ids.owner,memberUserId:ids.other,email:'other@example.com',role:'Viewer',status:'active',allClients:true,clientIds:[],canSendPayslips:false,createdAt:1,updatedAt:1}));expect((await other.action(anyApi.compliance.overview,{businessId:ids.b,taxYear:2026})).canGenerate).toBe(false);await expect(other.action(anyApi.compliance.generate,{businessId:ids.b,taxYear:2026,formId:'annual_pack'})).rejects.toThrow();});
});
