/// <reference types="vite/client" />
import { beforeEach, afterEach, describe, it, expect, vi } from 'vitest';
import { convexTest } from 'convex-test';
import { anyApi } from 'convex/server';
import schema from '../convex/schema';
import { ACCOUNTANT_PLANS } from '../shared/accountantPlans';
import { miaInstructions } from '../shared/miaKnowledge';
const modules=import.meta.glob('../convex/**/*.{ts,js}');const api=anyApi;
async function fixture(){const t=convexTest(schema,modules);await t.run(async ctx=>{await ctx.db.insert('users',{firebaseUid:'owner',email:'owner@example.com',plan:'accountant_yearly',planStatus:'active'});await ctx.db.insert('users',{firebaseUid:'other',email:'other@example.com',plan:'free'});});return {t,owner:t.withIdentity({subject:'owner'}),other:t.withIdentity({subject:'other'})};}
const request=(token?:string)=>({token,requestId:crypto.randomUUID(),name:'Test User',email:'user@example.com',subject:'Cannot download',description:'Please help me download my payslip.',page:'/accountant',transcript:'',consent:false,website:''});
beforeEach(()=>{vi.useFakeTimers();vi.setSystemTime(new Date('2026-10-01T00:00:00Z'));});afterEach(()=>{vi.useRealTimers();vi.unstubAllGlobals();vi.unstubAllEnvs();});
describe('Mia private support',()=>{
 it('anonymous chat requires a minted session and expires after 24h',async()=>{const {t}=await fixture();await expect(t.action(api.mia.chat,{message:'Help',history:[],page:'/'})).rejects.toThrow('SUPPORT_SESSION_EXPIRED');const s=await t.mutation(api.miaInternal.issueSession,{});expect(s.token.length).toBe(72);vi.setSystemTime(new Date('2026-10-02T00:00:01Z'));await expect(t.action(api.mia.chat,{token:s.token,message:'Help',history:[],page:'/'})).rejects.toThrow('SUPPORT_SESSION_EXPIRED');});
 it('identity is server-derived, context contains no employee information, and support uses no Cayla counters',async()=>{const {t,owner,other}=await fixture();vi.stubEnv('OPENAI_API_KEY','test');let bodies:any[]=[];vi.stubGlobal('fetch',vi.fn(async(_,init:any)=>{bodies.push(JSON.parse(init.body));return new Response(JSON.stringify({output:[{type:'message',content:[{type:'output_text',text:'See [pricing](/pricing).'}]}]}));}));const args={message:'What is my plan?',history:[],page:'/accountant?bank=secret'};expect((await owner.action(api.mia.chat,args)).ok).toBe(true);await other.action(api.mia.chat,args);expect(bodies[0].instructions).toContain('"plan":"accountant_yearly"');expect(bodies[1].instructions).toContain('"plan":"free"');expect(bodies[1].instructions).not.toContain('user:owner');expect(bodies[0].instructions).not.toContain('bank=secret');expect(bodies[0]).toMatchObject({store:false,max_output_tokens:650});expect(await t.run(ctx=>ctx.db.query('usageCounters').collect())).toHaveLength(0);});
 it('rate reserves atomically before provider calls, anonymous token rotation cannot bypass global budgets',async()=>{const {t}=await fixture();const s=await t.mutation(api.miaInternal.issueSession,{});vi.stubEnv('OPENAI_API_KEY','test');const provider=vi.fn().mockResolvedValue(new Response(JSON.stringify({output:[]})));vi.stubGlobal('fetch',provider);for(let i=0;i<4;i++)await t.action(api.mia.chat,{token:s.token,message:'Help',history:[],page:'/'});await expect(t.action(api.mia.chat,{token:s.token,message:'Help',history:[],page:'/'})).rejects.toThrow('SUPPORT_RATE_LIMITED');expect(provider).toHaveBeenCalledTimes(4);await t.run(async ctx=>{const row=await ctx.db.query('miaRates').withIndex('by_key',q=>q.eq('key',`chat:global:anon:${Math.floor(Date.now()/86400000)}`)).first();await ctx.db.patch(row!._id,{count:200});});const other=await t.mutation(api.miaInternal.issueSession,{});await expect(t.action(api.mia.chat,{token:other.token,message:'Help',history:[],page:'/'})).rejects.toThrow('SUPPORT_RATE_LIMITED');expect(provider).toHaveBeenCalledTimes(4);});
 it('missing configuration and OpenAI outage provide human support fallback; oversized input is denied',async()=>{const {owner}=await fixture();const args={message:'Help',history:[],page:'/'};expect(await owner.action(api.mia.chat,args)).toMatchObject({ok:false});vi.stubEnv('OPENAI_API_KEY','test');vi.stubGlobal('fetch',vi.fn().mockRejectedValue(new Error('secret provider details')));const response=await owner.action(api.mia.chat,args);expect(response.ok).toBe(false);expect(response.error).not.toContain('secret');await expect(owner.action(api.mia.chat,{...args,message:'x'.repeat(2001)})).rejects.toThrow();});
 it('knowledge uses canonical pricing and differentiates policies',()=>{const prompt=miaInstructions({});expect(prompt).toContain(ACCOUNTANT_PLANS.accountant_yearly.priceLabel);expect(prompt).toContain('Google Play');expect(prompt).toContain('do not');expect(prompt).toContain('Paddle');expect(prompt).toContain('not annual allowances');});
 it('email success requires Resend acceptance, retries are idempotent and acknowledgement is separate',async()=>{const {owner,t}=await fixture();vi.stubEnv('RESEND_API_KEY','test');const calls:any[]=[];vi.stubGlobal('fetch',vi.fn(async(_,init:any)=>{calls.push({body:JSON.parse(init.body),headers:init.headers});return new Response(JSON.stringify({id:`email-${calls.length}`}));}));const args=request();let result=await owner.action(api.mia.submitRequest,args);expect(result).toMatchObject({ok:true,acknowledged:true});const again=await owner.action(api.mia.submitRequest,args);expect(again.reference).toBe(result.reference);expect(calls).toHaveLength(2);expect(calls[0].body).toMatchObject({to:['support@sheetpay.app'],reply_to:'user@example.com'});expect(calls[0].body.text).toContain('No transcript included');expect(calls[1].body.to).toEqual(['user@example.com']);expect(calls[0].headers['Idempotency-Key']).toContain('mia-ticket');expect((await t.run(ctx=>ctx.db.query('miaRequests').collect()))[0].status).toBe('accepted');});
 it('failure retains a request for retry; transcripts require explicit consent and spam input fails',async()=>{const {owner,t}=await fixture();vi.stubEnv('RESEND_API_KEY','test');const args=request();await expect(owner.action(api.mia.submitRequest,{...args,transcript:'private',consent:false})).rejects.toThrow('consent');await expect(owner.action(api.mia.submitRequest,{...args,website:'spam'})).rejects.toThrow();let fail=true;vi.stubGlobal('fetch',vi.fn(async()=>new Response(JSON.stringify(fail?{message:'invalid'}:{id:'accepted'}),{status:fail?400:200})));expect((await owner.action(api.mia.submitRequest,args)).ok).toBe(false);expect((await t.run(ctx=>ctx.db.query('miaRequests').collect()))[0].status).toBe('failed');fail=false;expect((await owner.action(api.mia.submitRequest,args)).ok).toBe(true);expect(await t.run(ctx=>ctx.db.query('miaRequests').collect())).toHaveLength(1);});
 it('acknowledgement failure does not discard an accepted ticket and retry is idempotent',async()=>{const {owner,t}=await fixture();vi.stubEnv('RESEND_API_KEY','test');let ackFails=true;vi.stubGlobal('fetch',vi.fn(async(_,init:any)=>{const data=JSON.parse(init.body);const fail=data.to[0]==='user@example.com'&&ackFails;return new Response(JSON.stringify(fail?{message:'invalid'}:{id:'accepted'}),{status:fail?400:200});}));const args=request();expect(await owner.action(api.mia.submitRequest,args)).toMatchObject({ok:true,acknowledged:false});ackFails=false;await t.action(api.mia.retryAcknowledgements,{});expect(await owner.action(api.mia.submitRequest,args)).toMatchObject({ok:true,acknowledged:true});await expect(owner.action(api.mia.submitRequest,{...args,description:'Changed'})).rejects.toThrow('new support request');});
 it('different accounts cannot reuse a ticket or retrieve another account context',async()=>{const {owner,other,t}=await fixture();vi.stubEnv('RESEND_API_KEY','test');vi.stubGlobal('fetch',vi.fn(async()=>new Response(JSON.stringify({id:'accepted'}))));const args=request();const a=await owner.action(api.mia.submitRequest,args);const b=await other.action(api.mia.submitRequest,args);expect(a.reference).not.toBe(b.reference);const rows=await t.run(ctx=>ctx.db.query('miaRequests').collect());expect(rows[0].context.plan).toBe('accountant_yearly');expect(rows[1].context.plan).toBe('free');});
 it('retention removes expired sessions, rate records and requests',async()=>{const {t,owner}=await fixture();await t.mutation(api.miaInternal.issueSession,{});vi.stubEnv('RESEND_API_KEY','test');vi.stubGlobal('fetch',vi.fn(async()=>new Response(JSON.stringify({id:'accepted'}))));await owner.action(api.mia.submitRequest,request());vi.setSystemTime(new Date('2027-02-01T00:00:00Z'));await t.mutation(api.miaInternal.purgeExpired,{});for(const table of ['miaSessions','miaRates','miaRequests'] as const)expect(await t.run(ctx=>ctx.db.query(table).collect())).toHaveLength(0);});
});
