/// <reference types="vite/client" />
import { describe,it,expect,vi,afterEach } from 'vitest';
import { convexTest } from 'convex-test';
import { anyApi } from 'convex/server';
import schema from '../convex/schema';
const modules=import.meta.glob('../convex/**/*.{ts,js}');const api=anyApi;
async function fixture(){const t=convexTest(schema,modules);const ids=await t.run(async ctx=>{const a=await ctx.db.insert('users',{firebaseUid:'security-a',email:'a@example.com'});const b=await ctx.db.insert('users',{firebaseUid:'security-b',email:'b@example.com'});await ctx.db.insert('messages',{userId:b,sender:'user',text:'Private payroll discussion',timestamp:'today',createdAt:Date.now()});await ctx.db.insert('emailLogs',{userId:String(b),recipient:'worker@example.com',subject:'Private payslip',emailType:'employeePayslip',status:'sent',createdAt:Date.now()});return{a,b};});return{t,ids,a:t.withIdentity({subject:'security-a',email:'a@example.com'})};}
afterEach(()=>vi.unstubAllGlobals());
describe('Privacy and backend authorization',()=>{
 it('rejects anonymous and cross-account message access and deletion',async()=>{const{t,ids,a}=await fixture();await expect(t.query(api.messages.getByUser,{userId:ids.b})).rejects.toThrow('Unauthenticated');await expect(a.query(api.messages.getByUser,{userId:ids.b})).rejects.toThrow('Forbidden');await expect(a.mutation(api.messages.clearByUser,{userId:ids.b})).rejects.toThrow('Forbidden');expect(await t.run(ctx=>ctx.db.query('messages').collect())).toHaveLength(1);});
 it('keeps email metadata private and prevents preference tampering',async()=>{const{t,ids,a}=await fixture();await expect(t.query(api.emailLogs.getEmailLogs,{})).rejects.toThrow('Unauthenticated');await expect(a.query(api.emailLogs.getEmailLogs,{userId:String(ids.b)})).rejects.toThrow('Forbidden');expect(await a.query(api.emailLogs.getEmailLogs,{})).toEqual([]);await expect(a.mutation(api.emailPreferences.updateMine,{userId:'security-b',payroll:false})).rejects.toThrow('Forbidden');await a.mutation(api.emailPreferences.updateMine,{userId:'security-a',security:false});expect(await a.query(api.emailPreferences.getMine,{userId:'security-a'})).toMatchObject({security:true});});
 it('blocks unauthenticated AI before any provider call',async()=>{const{t}=await fixture();const fetch=vi.fn();vi.stubGlobal('fetch',fetch);await expect(t.action(api.mobileAi.generatePayslip,{prompt:'Create a payslip'})).rejects.toThrow('Unauthenticated');await expect(t.action(api.mobileAi.extractPayslip,{base64Data:'aGVsbG8=',mimeType:'image/png'})).rejects.toThrow('Unauthenticated');expect(fetch).not.toHaveBeenCalled();});
 it('does not allow forged usage identities or reuse another reservation',async()=>{const{t,a}=await fixture();await expect(a.query(api.betaUsage.getForUser,{firebaseUid:'security-b'})).rejects.toThrow('Unauthenticated');await expect(a.mutation(api.betaUsage.reserve,{firebaseUid:'security-b',kind:'ocr',requestId:'forged-reservation'})).rejects.toThrow('Unauthenticated');await a.mutation(api.betaUsage.reserve,{firebaseUid:'security-a',kind:'ocr',requestId:'same-reservation'});const b=t.withIdentity({subject:'security-b'});await expect(b.mutation(api.betaUsage.reserve,{firebaseUid:'security-b',kind:'ocr',requestId:'same-reservation'})).rejects.toThrow();});
 it('purges expired retired drafts without deleting user accounts',async()=>{const{t,ids}=await fixture();await t.run(ctx=>ctx.db.insert('guestSessions',{anonSessionId:'a'.repeat(48),createdAt:1,updatedAt:1,expiresAt:1,guestClientsUsed:0,guestEmployeesUsed:0,guestPayrollRunsUsed:0,caylaActionsUsed:0,ocrScansUsed:0}));await t.mutation(api.privacyRetention.purgeExpiredAttachments,{});expect(await t.run(ctx=>ctx.db.query('guestSessions').collect())).toHaveLength(0);expect(await t.run(ctx=>ctx.db.get(ids.a))).toBeTruthy();});
});
