/// <reference types="vite/client" />
import { afterEach, beforeEach, describe, expect, it, vi } from "vitest";
import { convexTest } from "convex-test";
import { anyApi } from "convex/server";
import schema from "../convex/schema";
function newCampaign(cayla=false){return {title:"Fixture campaign",country:"General Caribbean",persona:"Accountant",painPoint:"Managing payroll",format:cayla?"Cayla Demo":"POV",tone:"Natural",hook:"Payroll needs a clear workflow.",script:"Payroll needs a clear workflow. Review and approve.",captions:"Payroll needs a clear workflow.",cta:"Explore Sheetpay Accountant.",socialCaption:"Prepare payroll with user review.",headline:"Payroll workflow",approvedClaims:"",claimsApproved:false,reviewApproved:false,duration:30,aspectRatio:"9:16",model:"grok-imagine-text-to-video",resolution:"720p",captionsEnabled:true,scenes:[{key:"hook",kind:"creator",label:"Hook",duration:30,text:"Payroll needs a clear workflow.",prompt:"Fictional adult presenter"}]};}
import { muapi, clipLengths, payloadFor, ProviderError, providerMessage } from "../convex/lib/ugcProvider";
import { latestJobs } from "../convex/lib/ugcPolicy";
const modules=import.meta.glob("../convex/**/*.{ts,js}");
const model={name:"grok-imagine-text-to-video",is_enabled:1,dynamic_pricing:true,estimate_endpoint:"/api/v1/models/grok-imagine-text-to-video/estimate-cost",input_schema:{schemas:{input_data:{required:["prompt"],properties:{prompt:{type:"string"},duration:{type:"int",minValue:6,maxValue:30},aspect_ratio:{type:"string",enum:["9:16","16:9"]},resolution:{type:"string",enum:["480p","720p"]},mode:{type:"string",enum:["normal"]}}}}}};
async function setup(){const t=convexTest(schema,modules);await t.run(async ctx=>{await ctx.db.insert("users",{firebaseUid:"admin",email:"surebookme@gmail.com",emailVerified:true});await ctx.db.insert("users",{firebaseUid:"regular",email:"someone@example.com",emailVerified:true});});return {t,admin:t.withIdentity({subject:"admin",email:"surebookme@gmail.com",emailVerified:true}),regular:t.withIdentity({subject:"regular",email:"someone@example.com",emailVerified:true})};}
beforeEach(()=>{vi.useFakeTimers();vi.stubEnv("MUAPI_API_KEY","test-key-not-real");});
afterEach(()=>{vi.clearAllTimers();vi.useRealTimers();vi.unstubAllEnvs();vi.unstubAllGlobals();vi.restoreAllMocks();});
describe("UGC admin security and persistence",()=>{
  it("denies anonymous, regular and unverified administrators",async()=>{const {t,regular}=await setup();expect(await t.query(anyApi.ugc.access,{})).toEqual({authorized:false});expect(await regular.query(anyApi.ugc.access,{})).toEqual({authorized:false});await expect(regular.query(anyApi.ugc.dashboard,{})).rejects.toThrow("SOCIAL_ADMIN_REQUIRED");await expect(t.mutation(anyApi.ugc.save,newCampaign())).rejects.toThrow("SOCIAL_ADMIN_REQUIRED");const unverified=t.withIdentity({subject:"admin",email:"surebookme@gmail.com",emailVerified:false});await expect(unverified.mutation(anyApi.ugc.save,newCampaign())).rejects.toThrow("SOCIAL_ADMIN_REQUIRED");});
  it("saves and edits a campaign with revision conflict detection",async()=>{const {admin}=await setup(),c=newCampaign(true),id=await admin.mutation(anyApi.ugc.save,c);await admin.mutation(anyApi.ugc.save,{...c,id,expectedRevision:1,title:"Updated"});await expect(admin.mutation(anyApi.ugc.save,{...c,id,expectedRevision:1})).rejects.toThrow("another window");const row=(await admin.query(anyApi.ugc.dashboard,{})).campaigns[0];expect(row).toMatchObject({title:"Updated",revision:2,status:"draft"});});
  it("validates country, duration, totals and claims confirmation",async()=>{const {admin}=await setup();for(const patch of [{country:"Unsupported"},{duration:90},{scenes:[{key:"x",kind:"creator",label:"x",duration:20,text:"",prompt:""}]},{approvedClaims:"A verified result",claimsApproved:false}])await expect(admin.mutation(anyApi.ugc.save,{...newCampaign(),...patch})).rejects.toThrow();});
  it("duplicates a selected hook without reusing approval or output",async()=>{const {admin}=await setup(),c={...newCampaign(),reviewApproved:true},id=await admin.mutation(anyApi.ugc.save,c);const copy=await admin.mutation(anyApi.ugc.duplicate,{id,hook:"A new fictional presenter hook"});const row=(await admin.query(anyApi.ugc.dashboard,{})).campaigns.find((x:any)=>x._id===copy);expect(row).toMatchObject({hook:"A new fictional presenter hook",reviewApproved:false,status:"draft",revision:1});expect(row.scenes[0].text).toBe(row.hook);expect(row.videoStorageId).toBeUndefined();});
  it("keeps empty summaries based on actual data",async()=>{const {admin}=await setup();expect((await admin.query(anyApi.ugc.dashboard,{})).summary).toMatchObject({videosGenerated:0,estimatedSpend:0,actualSpend:0,failed:0});});
  it("requires rights confirmation and an actor image for creators",async()=>{const {admin}=await setup();await expect(admin.mutation(anyApi.ugc.saveCreator,{label:"Creator",persona:"Accountant",notes:"",preferredModel:"grok-imagine-text-to-video",rightsConfirmed:false})).rejects.toThrow("consent");const id=await admin.mutation(anyApi.ugc.saveCreator,{label:"Fictional accountant",persona:"Accountant",notes:"Casual",preferredModel:"grok-imagine-text-to-video",rightsConfirmed:true});expect((await admin.query(anyApi.ugc.dashboard,{})).creators[0]._id).toBe(id);});
  it("rejects upload metadata mismatches and oversized uploads",async()=>{const {t,admin}=await setup();await expect(admin.mutation(anyApi.ugc.beginUpload,{size:101*1024*1024,contentType:"video/mp4",sha256:"A".repeat(43)+"="})).rejects.toThrow("100 MB");const sid=await t.run(ctx=>ctx.storage.store(new Blob(["test"],{type:"image/png"})));const ticket=await admin.mutation(anyApi.ugc.beginUpload,{size:100,contentType:"video/mp4",sha256:"A".repeat(43)+"="});await expect(admin.mutation(anyApi.ugc.finishUpload,{ticket:ticket.ticket,storageId:sid,label:"x",category:"dashboard"})).rejects.toThrow("verified");await expect(admin.query(anyApi.ugc.asset,{id:sid})).rejects.toThrow("not found");});
  it("registers a verified media upload and prevents ticket replay",async()=>{const {t,admin}=await setup();const sid=await t.run(ctx=>ctx.storage.store(new Blob(["sample"],{type:"image/png"})));await t.run(ctx=>ctx.db.patch(sid as any,{contentType:"image/png"} as any));const meta=await t.run(ctx=>ctx.db.system.get(sid));const ticket=await admin.mutation(anyApi.ugc.beginUpload,{size:meta!.size,contentType:meta!.contentType!,sha256:meta!.sha256});const args={ticket:ticket.ticket,storageId:sid,label:"Demonstration screenshot",category:"screenshot"};await admin.mutation(anyApi.ugc.finishUpload,args);expect(await admin.query(anyApi.ugc.asset,{id:sid})).toBe(sid);await expect(admin.mutation(anyApi.ugc.finishUpload,args)).rejects.toThrow("verified");});
});
describe("UGC paid-generation safeguards",()=>{
  it("requires explicit cost confirmation and consumes a quote once",async()=>{
    const {t,admin}=await setup();const c={...newCampaign(),reviewApproved:true},id=await admin.mutation(anyApi.ugc.save,c);const ownerId=(await admin.query(anyApi.ugc.access,{})).ownerId;
    const quoteId=await t.mutation(anyApi.ugc.storeQuote,{campaignId:id,ownerId,revision:1,amount:0.3,items:[{sceneKey:"hook:0",model:c.model,duration:6,amount:0.3,payload:{prompt:"Fictional actor",duration:6,resolution:"720p",aspect_ratio:"9:16"}}]});
    await expect(admin.mutation(anyApi.ugc.generate,{quoteId,confirmed:false})).rejects.toThrow("Generate Video");
    await Promise.all([admin.mutation(anyApi.ugc.generate,{quoteId,confirmed:true}),admin.mutation(anyApi.ugc.generate,{quoteId,confirmed:true})]);
    const jobs=(await admin.query(anyApi.ugc.dashboard,{})).jobs;expect(jobs).toHaveLength(1);expect(jobs[0].estimatedCost).toBe(0.3);expect(jobs[0].payload).toBeUndefined();
    const first=await t.mutation(anyApi.ugc.claimSubmit,{id:jobs[0]._id});expect(first).not.toBeNull();expect(await t.mutation(anyApi.ugc.claimSubmit,{id:jobs[0]._id})).toBeNull();
    await expect(admin.mutation(anyApi.ugc.save,{...c,id,expectedRevision:1})).rejects.toThrow("uncertain");await expect(admin.mutation(anyApi.ugc.retryStatus,{id:jobs[0]._id})).rejects.toThrow("reconcile");
  });
  it("does not enqueue paid requests without a configured provider key",async()=>{const {t,admin}=await setup(),c={...newCampaign(),reviewApproved:true},id=await admin.mutation(anyApi.ugc.save,c),ownerId=(await admin.query(anyApi.ugc.access,{})).ownerId;const q=await t.mutation(anyApi.ugc.storeQuote,{campaignId:id,ownerId,revision:1,amount:0.1,items:[]});vi.stubEnv("MUAPI_API_KEY","");await expect(admin.mutation(anyApi.ugc.generate,{quoteId:q,confirmed:true})).rejects.toThrow("MUAPI_API_KEY");expect((await admin.query(anyApi.ugc.dashboard,{})).jobs).toHaveLength(0);});
  it("blocks stale and expired estimates",async()=>{const {t,admin}=await setup(),c={...newCampaign(),reviewApproved:true},id=await admin.mutation(anyApi.ugc.save,c),ownerId=(await admin.query(anyApi.ugc.access,{})).ownerId;const q=await t.mutation(anyApi.ugc.storeQuote,{campaignId:id,ownerId,revision:1,amount:0.1,items:[]});await admin.mutation(anyApi.ugc.save,{...c,id,expectedRevision:1,title:"Changed"});await expect(admin.mutation(anyApi.ugc.generate,{quoteId:q,confirmed:true})).rejects.toThrow("changed");});
  it("uses the newest attempt for each scene when showing completion",()=>{const result=latestJobs([{sceneKey:"hook:0",createdAt:1,status:"failed"},{sceneKey:"hook:0",createdAt:2,status:"completed"}]);expect(result).toHaveLength(1);expect(result[0].status).toBe("completed");});
});
describe("MuAPI official contract adapter",()=>{
  it("splits short-limit models without inventing supported lengths",()=>{expect(clipLengths(60,model)).toEqual([30,30]);expect(clipLengths(4,model)).toEqual([6]);const veo={...model,input_schema:{schemas:{input_data:{properties:{duration:{enum:[8]}}}}}};expect(clipLengths(15,veo)).toEqual([8,8]);});
  it("uses documented payload fields and rejects unsupported resolutions",()=>{expect(payloadFor(model,"fictional actor",6,"720p")).toEqual({prompt:"fictional actor",duration:6,aspect_ratio:"9:16",resolution:"720p",mode:"normal"});expect(()=>payloadFor(model,"actor",6,"1080p")).toThrow("PARAMS");const imageModel={...model,input_schema:{schemas:{input_data:{required:["prompt","images_list"],properties:{...model.input_schema.schemas.input_data.properties,images_list:{type:"array",maxItems:7}}}}}};expect(payloadFor(imageModel,"actor",6,"720p","https://example.com/actor.png").images_list).toEqual(["https://example.com/actor.png"]);expect(()=>payloadFor(imageModel,"actor",6,"720p")).toThrow("PARAMS");});
  it("fetches live estimates without submitting a generation",async()=>{const calls:string[]=[];vi.stubGlobal("fetch",vi.fn(async(url:string,init:any)=>{calls.push(url);if(url.endsWith("estimate-cost")){expect(JSON.parse(init.body).duration).toBe(6);return Response.json({cost:0.3,currency:"USD"});}return Response.json(model);}));expect(await muapi.estimateCost(model.name,payloadFor(model,"actor",6,"720p"))).toBe(0.3);expect(calls).toEqual(["https://api.muapi.ai/api/v1/models/grok-imagine-text-to-video","https://api.muapi.ai/api/v1/models/grok-imagine-text-to-video/estimate-cost"]);});
  it("treats lost paid responses as uncertain and masks provider details",async()=>{vi.stubGlobal("fetch",vi.fn(async()=>{throw new Error("secret raw upstream failure");}));try{await muapi.generate(model.name,{prompt:"actor"});throw new Error("unexpected");}catch(e){expect(e).toBeInstanceOf(ProviderError);expect((e as ProviderError).ambiguous).toBe(true);expect(providerMessage(e)).not.toContain("secret");}});
  it("maps insufficient credits and invalid parameters to actionable messages",async()=>{vi.stubGlobal("fetch",vi.fn(async()=>new Response("secret",{status:402})));await expect(muapi.generate(model.name,{})).rejects.toMatchObject({code:"CREDITS",ambiguous:false});expect(providerMessage(new ProviderError("CREDITS"))).toContain("Top up");});
});
