/// <reference types="vite/client" />
import { afterEach, beforeEach, describe, expect, it, vi } from "vitest";
import { convexTest } from "convex-test";
import { anyApi } from "convex/server";
import schema from "../convex/schema";
import { jsonModel } from "../convex/socialWorker";
vi.mock("../convex/socialWorker",()=>({jsonModel:vi.fn()}));
const modules=import.meta.glob("../convex/**/*.{ts,js}");
const c={title:"Cayla campaign",country:"General Caribbean",persona:"Accountant",painPoint:"Payroll administration",format:"Cayla Demo",tone:"Natural",hook:"Prepare payroll, then review.",script:"Prepare payroll, then review.",captions:"Prepare payroll, then review.",cta:"Explore Sheetpay Accountant",socialCaption:"Review and approve.",headline:"Payroll workflow",approvedClaims:"",claimsApproved:false,reviewApproved:true,duration:30,aspectRatio:"9:16",model:"grok-imagine-text-to-video",resolution:"720p",captionsEnabled:true,scenes:[{key:"hook",kind:"creator",label:"Hook",duration:30,text:"Prepare payroll, then review.",prompt:"Fictional adult accountant"}]};
const m={name:c.model,is_enabled:1,dynamic_pricing:true,estimate_endpoint:`/api/v1/models/${c.model}/estimate-cost`,input_schema:{schemas:{input_data:{required:["prompt"],properties:{prompt:{type:"string"},duration:{type:"int",minValue:6,maxValue:30},aspect_ratio:{enum:["9:16"]},resolution:{enum:["720p"]},mode:{enum:["normal"]}}}}}};
async function setup(){const t=convexTest(schema,modules);await t.run(ctx=>ctx.db.insert("users",{firebaseUid:"admin",email:"surebookme@gmail.com",emailVerified:true}));const admin=t.withIdentity({subject:"admin",email:"surebookme@gmail.com",emailVerified:true}),id=await admin.mutation(anyApi.ugc.save,c);return {t,admin,id};}
beforeEach(()=>{vi.useFakeTimers();vi.stubEnv("MUAPI_API_KEY","fixture-key");vi.stubEnv("OPENAI_API_KEY","fixture-openai-key");vi.mocked(jsonModel).mockReset();});afterEach(()=>{vi.clearAllTimers();vi.useRealTimers();vi.unstubAllGlobals();vi.unstubAllEnvs();});
describe("script and hook generation",()=>{
 it("uses the shared OpenAI JSON helper and reviews script claims",async()=>{const {admin,id}=await setup();vi.mocked(jsonModel).mockResolvedValueOnce({hook:c.hook,script:c.script,captions:c.captions,cta:c.cta,socialCaption:c.socialCaption,headline:c.headline,scenes:c.scenes}).mockResolvedValueOnce({safe:true});const result=await admin.action(anyApi.ugcWorker.write,{id,kind:"script",instruction:"Make it natural"});expect(result.scenes[0].kind).toBe("creator");expect(jsonModel).toHaveBeenCalledTimes(2);expect(vi.mocked(jsonModel).mock.calls[0][0]).toContain("user reviews and approves");});
 it("returns the requested hook count and rejects unsupported claims",async()=>{const {admin,id}=await setup(),hooks=Array.from({length:5},(_,i)=>({category:"POV",text:"Payroll workflow "+i}));vi.mocked(jsonModel).mockResolvedValueOnce({hooks}).mockResolvedValueOnce({safe:true});expect((await admin.action(anyApi.ugcWorker.write,{id,kind:"hooks",count:5,instruction:""})).hooks).toHaveLength(5);vi.mocked(jsonModel).mockResolvedValueOnce({hooks}).mockResolvedValueOnce({safe:false});await expect(admin.action(anyApi.ugcWorker.write,{id,kind:"hooks",count:5,instruction:""})).rejects.toThrow("claims review");});
 it("rejects malformed scripts and invalid hook batch sizes",async()=>{const {admin,id}=await setup();vi.mocked(jsonModel).mockResolvedValueOnce({script:"bad"});await expect(admin.action(anyApi.ugcWorker.write,{id,kind:"script",instruction:""})).rejects.toThrow();await expect(admin.action(anyApi.ugcWorker.write,{id,kind:"hooks",count:100,instruction:""})).rejects.toThrow("5, 10 or 20");});
});
describe("asynchronous provider jobs",()=>{
 it("quotes a 60-second scene as two clips with live pricing",async()=>{const {t,admin,id}=await setup();await admin.mutation(anyApi.ugc.save,{...c,id,expectedRevision:1,duration:60,scenes:[{...c.scenes[0],duration:60}]});const calls:string[]=[];vi.stubGlobal("fetch",vi.fn(async(url:string)=>{calls.push(url);return Response.json(url.endsWith("estimate-cost")?{cost:1.5,currency:"USD"}:m);}));const quote=await admin.action(anyApi.ugcWorker.estimate,{id});expect(quote.items).toHaveLength(2);expect(quote.amount).toBe(3);expect(quote.items.map((x:any)=>x.duration)).toEqual([30,30]);expect(calls.every(x=>x.includes("/models/"))).toBe(true);expect((await t.run(ctx=>ctx.db.query("ugcQuotes").collect())).length).toBe(1);});
 it("submits only once even if the worker runs twice",async()=>{const {t,admin,id}=await setup();let paidCalls=0;vi.stubGlobal("fetch",vi.fn(async(url:string,init:any)=>{if(url.endsWith("estimate-cost"))return Response.json({cost:1.5,currency:"USD"});if(url.includes("/models/"))return Response.json(m);paidCalls++;expect(init.headers["x-api-key"]).toBe("fixture-key");return Response.json({request_id:"provider-job",cost:{amount_usd:1.5}});}));const q=await admin.action(anyApi.ugcWorker.estimate,{id});await admin.mutation(anyApi.ugc.generate,{quoteId:q.quoteId,confirmed:true});const job=(await admin.query(anyApi.ugc.dashboard,{})).jobs[0];await Promise.all([t.action(anyApi.ugcWorker.submit,{id:job._id}),t.action(anyApi.ugcWorker.submit,{id:job._id})]);expect(paidCalls).toBe(1);expect((await admin.query(anyApi.ugc.dashboard,{})).jobs[0]).toMatchObject({providerJobId:"provider-job",actualCost:1.5,outcomeUnknown:false});});
 it("saves completed video output in protected storage",async()=>{const {t,admin,id}=await setup();const ownerId=(await admin.query(anyApi.ugc.access,{})).ownerId;const job=await t.run(ctx=>ctx.db.insert("ugcJobs",{campaignId:id,ownerId,revision:1,sceneKey:"hook:0",model:c.model,payload:{},estimatedCost:1,status:"generating",providerJobId:"provider-job",outcomeUnknown:false,pollCount:0,createdAt:Date.now(),updatedAt:Date.now()}));vi.stubGlobal("fetch",vi.fn(async(url:string)=>url.includes("predictions")?Response.json({status:"completed",outputs:["https://cdn.muapi.ai/video.mp4"],cost:{amount_usd:0.8,refunded:false}}):new Response(new Blob(["mock video"],{type:"video/mp4"}),{headers:{"Content-Type":"video/mp4"}})));await t.action(anyApi.ugcWorker.poll,{id:job,manual:false});const j=(await admin.query(anyApi.ugc.dashboard,{})).jobs[0];expect(j).toMatchObject({status:"completed",actualCost:0.8});expect(j.storageId).toBeDefined();expect(await admin.query(anyApi.ugc.asset,{id:j.storageId})).toBe(j.storageId);expect(j.outputUrl).toBeUndefined();});
 it("marks provider failure and allows retrying the same request without paying again",async()=>{const {t,admin,id}=await setup(),ownerId=(await admin.query(anyApi.ugc.access,{})).ownerId;const job=await t.run(ctx=>ctx.db.insert("ugcJobs",{campaignId:id,ownerId,revision:1,sceneKey:"hook:0",model:c.model,payload:{},estimatedCost:1,status:"generating",providerJobId:"provider-job",outcomeUnknown:false,pollCount:0,createdAt:Date.now(),updatedAt:Date.now()}));vi.stubGlobal("fetch",vi.fn(async()=>Response.json({status:"failed",error:"secret stack trace",cost:{amount_usd:1,refunded:true}})));await t.action(anyApi.ugcWorker.poll,{id:job,manual:false});const j=(await admin.query(anyApi.ugc.dashboard,{})).jobs[0];expect(j.status).toBe("failed");expect(j.error).not.toContain("secret");expect((await admin.query(anyApi.ugc.dashboard,{})).summary.actualSpend).toBe(0);await admin.mutation(anyApi.ugc.retryStatus,{id:job});expect((await admin.query(anyApi.ugc.dashboard,{})).jobs).toHaveLength(1);});
});
