// Immutable released configuration. Add a new version rather than editing mappings
// used by an existing generation. No tax rates are recalculated by these reports.
export const COMPLIANCE_VERSION = 'payroll-records-2026-v1';
export const DISCLAIMER = 'Sheetpay generates payroll and compliance reports using the payroll information available in your workspace. Review all information before filing. Filing requirements may change and final responsibility for submission remains with the employer or authorized tax professional.';
export const SOURCES: Record<string, {name:string;flag:string;authority:string;url:string;contributionUrl:string}> = {
 TT:{name:'Trinidad & Tobago',flag:'🇹🇹',authority:'Inland Revenue Division / NIBTT',url:'https://www.ird.gov.tt/Forms',contributionUrl:'https://www.nibtt.net/NI_Payment_Registration/Instructions-Online%20Payment.html'},
 LC:{name:'Saint Lucia',flag:'🇱🇨',authority:'Inland Revenue Department / NIC',url:'https://irdstlucia.gov.lc/images/Documents/Publications/Employers_PAYE_Guide_printP.pdf',contributionUrl:'https://attorneygeneralchambers.com/laws-of-saint-lucia/national-insurance-corporation-act/schedule-2-01'},
 BB:{name:'Barbados',flag:'🇧🇧',authority:'Barbados Revenue Authority / NIS',url:'https://bra.gov.bb/Popular-Topics/Companies/Third-Party-Returns',contributionUrl:'https://www.nis.gov.bb/portal/'},
 BZ:{name:'Belize',flag:'🇧🇿',authority:'Belize Tax Service / Social Security Board',url:'https://irisbelize.bts.gov.bz/Returns/ReturnDownloads',contributionUrl:'https://socialsecurity.org.bz/employer-services/'},
};
export const TT_FIELDS = [
 ['td1Deductions','TD1 approved deductions'],['weeksEmployed','Weeks employed'],['remuneration','Remuneration before deductions'],['commissions','Commissions'],['it76','Taxable allowances / IT76 total'],['travelAllowance','Taxable travelling allowance'],['otherAllowance','Other taxable allowance'],['previousIncome','Previous-year income paid this year'],['savingsPlan','Company savings plan withdrawals'],['employerPension','Employer approved fund contributions'],['travelDispensation','Approved travelling dispensation'],['employeePension','Employee approved pension contributions'],['healthWeeks','Health Surcharge total weeks'],['healthWeeks825','Health Surcharge weeks at $8.25'],['healthWeeks480','Health Surcharge weeks at $4.80'],
] as const;
export const BB_FIELDS = [ ['taxCode','Tax code'],['employmentStart','Employment start date (YYYY-MM-DD)'],['employmentEnd','Employment end date (blank if continuing)'],['pension','Provident / superannuation deductions'],['travel','Travelling benefit'],['entertainment','Entertainment benefit'],['housing','Housing benefit'],['vehicle','Vehicle benefit'],['utilities','Utilities benefit'],['miscBenefits','Miscellaneous allowance / benefit'],['bonusShares','Bonus converted to shares'],['taxPaidSalary','Tax paid by employer on salary'],['taxPaidHousing','Tax paid by employer on housing'],['gratuity','Contract gratuity'],['basicMonthlySalary','Basic monthly salary'] ] as const;
export const IT76_FIELDS = [
 ['Motor Vehicle Registration NoEquipment','Vehicle registration / equipment','text'],['Value of benefit in kind','Vehicle / equipment benefit','number'],['Entertainment','Entertainment','number'],['Address and nature of accommodation 1','Accommodation address / nature','text'],['Address and nature of accommodation 2','Accommodation details','text'],['Name 1','Landlord name','text'],['Address','Landlord address','text'],['Fair rental value','Fair rental value','number'],['Rent paid','Rent paid by employee','number'],['Annual value of the use of furniture supplied by employer','Furniture benefit','number'],['Total b to e','Accommodation total (b–e)','number'],['Other expenses','Other expenses','number'],['Amount reimbursed','Amount reimbursed','number'],['Net Total','Other expenses net total','number'],['Club Subscriptions','Club subscriptions','number'],['Private Medical Dental etc treatment','Private medical / dental','number'],['Education of directors or employees family','Family education','number'],['Goods and Services','Goods and services','number'],['Work carried out','Work carried out','number'],['Employer contribution','Employer contributions','number'],['Loan interest','Loan interest benefit','number'],['Loans written off','Loans written off','number'],['Total a+b','Loan benefits total','number'],['Any other expense or benefit not included above','Other benefits','number']
] as const;
export function configuration(country:string, year:number) {
 if (!SOURCES[country]) throw new Error('Unsupported compliance country.');
 if (!Number.isInteger(year) || year < 2000 || year > new Date().getUTCFullYear()) throw new Error('Select a valid current or historical tax year.');
 const source=SOURCES[country];
 const common=[{id:'annual_pack',name:'Annual Compliance Pack',official:false},{id:'annual_payroll',name:'Annual payroll summary',official:false},{id:'employee_statement',name:'Employee annual earnings statement',official:false},{id:'paye_summary',name:'Annual PAYE summary (deducted)',official:false},{id:'monthly_statutory',name:'Monthly statutory summaries',official:false},{id:'contribution_summary',name:country==='LC'?'NIC Contribution Summary':country==='BZ'?'Social Security Contribution Summary':'NIS Contribution Summary',official:false}];
 const forms:any[] = country==='TT' ? [...common,{id:'surcharge_summary',name:'Health Surcharge Summary',official:false},{id:'td4',name:'TD4 Certificates',official:true},{id:'it76',name:'IT76',official:true}] : country==='BB' ? [...common,{id:'tamis_paye',name:'TAMIS PAYE Export / A47:004 data',official:true}] : country==='LC' ? [...common,{id:'td5',name:'TD5 Certificates',official:true,blocked:'The current official TD5 template cannot be verified while the IRD website is under maintenance. Use the employee statement to prepare the official form.'}] : [...common,{id:'iris_paye',name:'IRIS PAYE Export',official:true,blocked:'Current IRIS PAYE template/schema could not be verified. Use the PAYE preparation summary and official portal.'},{id:'bz_td4',name:'TD4 / employee PAYE preparation',official:true,blocked:'Current official Belize employee certificate layout is not verified. Use the annual earnings statement.'}];
 for(const f of forms){
 f.exportType=f.id==='tamis_paye'?'Official XLSX':f.official?'Official PDF':'Preparation PDF / CSV / XLSX';f.schemaVersion=`${country}-${year}-${COMPLIANCE_VERSION}`;f.validationRules=['Authenticated client access','Finalized payroll only','Employee identifiers complete','Reconcile stored payroll to employee snapshots','Form-specific reviewed classifications'];
 if(f.id==='td4'){f.templatePath='/compliance/templates/TT-TD4-revised.pdf';f.templateSha256='207f45370ede9a34cfa4b0e081359db4bf7046ccee74df34205fb87154575e48';f.officialSource='https://www.ird.gov.tt/Media/Default/IRDForms/PAYE/F-TD4_Supplementary--.pdf';}
 if(f.id==='it76'){f.templatePath='/compliance/templates/TT-IT76-2021.pdf';f.templateSha256='0f3774dfd21eda3cc708cd0efca62003a3cfc4f57c4ea83bd9815abaab917d18';f.officialSource='https://www.ird.gov.tt/Media/Default/IRDForms/PAYE/F-IT76--2021.pdf';}
 if(f.id==='tamis_paye'){f.templatePath='/compliance/templates/BB-PAYE-2019-2031.xlsx';f.templateSha256='aa723c3aa69855794376d3c18bd9d30a99da003d5c4c3ffba428aa9053aef964';f.officialSource=source.url;}
if(f.official && year>2026)f.blocked='Official requirements for this future year have not been verified.';if(f.official && ((country==='TT' && year<2021)||(country==='BB' && year<2019))) f.blocked='An official template for this historical year has not been verified.';}
 return {country,taxYear:year,version:`${country}-${year}-${COMPLIANCE_VERSION}`,effectiveFrom:`${year}-01-01`,effectiveTo:`${year}-12-31`,lastVerifiedAt:'2026-10-04',officialAuthority:source.authority,officialSource:source.url,contributionSource:source.contributionUrl,forms,requiredFields:['business.name','business.address','business.taxRegistrationId','employee.employeeId','employee.taxId','employee.contributionId'],calculationMappings:'Sum stored, finalized payroll snapshots in integer cents; do not recompute historical tax rates',exportTypes:['PDF','ZIP','CSV','XLSX']};
}
